### PR TITLE
V1.583

### PR DESCRIPTION
**Pull request by davelab6**
Here are the source file updates for the V1.583 to make a release from :)

Part of #16

### CODE REVIEW

**Comment by EbenSorkin** [comment]
This contains updates from Dave for version 1.583

**Comment by ErisDS** [comment]
What does it take for this to get updated on the Google CDN? I see it was merged 14 hours ago, but we're still seeing the issue. We're getting asked about it constantly so it would be good just to have some idea what to tell people. Thanks.

**Comment by davelab6** [comment]
The fix is being uploaded to the production API now

**Comment by ErisDS** [comment]
Thanks!

**Pull request merged**
