### PR TITLE
Expansion to GF Cyrillic Plus, Pro, and localised glyphs

### PR DESCRIPTION
**Pull request by alexeiva**
@EbenSorkin This is work in progress, please don't merge yet.

### CODE REVIEW

**Comment by alexeiva** [comment]
Now mastering and finalising the sources. 

Please don't merge this yet.

**Comment by alexeiva** [comment]
@EbenSorkin This is good to merge now

**Comment by alexeiva** [comment]
I have fixed some minor interpolation issues in the fonts, in connection with sources convertion to glyphs app. 

There remains a problem I don't know how to fix yet. 


Previous version — no ccmp = no problem
screen shot 2016-10-20 at 14 13 36

New Glyphs version Regular — ccmp works fine

screen shot 2016-10-20 at 14 14 10

New Glyphs version Italic — ccmp doesn't work properly

screen shot 2016-10-20 at 14 14 18

**Comment by alexeiva** [comment]
/cc @kalapi  @schriftgestalt Do you know why the `Aringacute` isn't placed properly? This glyph isn't in the font, but is produced thru mark positioning. 

https://github.com/alexeiva/Merriweather/blob/master/sources/Merriweather-Italic.glyphs

**Comment by kalapi** [comment]
@alexeiva The combining marks in the italics don't have a 'top' anchor and thus no resulting mkmk. Also, not entirely connected, the combining marks have advance widths (in both sources).

**Comment by alexeiva** [comment]
@kalapi Thanks, will try that. 
Combining marks have advanced widths in sources, but on TTF export glyphs zeros them automatically.

**Comment by schriftgestalt** [comment]
> Also, not entirely connected, the combining marks have advance widths (in both sources).
Yes, as @alexeiva said, on export, they are set to zero width. Zero width glyphs are difficult to edit in Glyphs because they sit on top of each other in the edit view.

**Comment by davelab6** [comment]
@alexeiva what is the status of this? waiting for @EbenSorkin to merge?

**Comment by alexeiva** [comment]
@davelab6 

Just made a fix for `Aringacute`. This is ready to merge now

screen shot 2016-10-28 at 00 17 12

**Pull request merged**
